### ISSUE TITLE
Permissão e divulgação

### ISSUE THREAD

**Issue by felipesousa** [mabrasil/slides-flisol-2015#1]
Brother, gostaria de pedir a permissão de usar o seu slides em uma apresentacao que pretendo fazer,  achei super foda a maneira como voce criou e queria pegar uma ajuda sua nisso! e ai ? rs

**Comment by ythecombinator** [comment]
E tu ainda pede? A vontade cara! E se quiser, posso dar uma ajuda nessa apresentação :smiley:

**Comment by felipesousa** [comment]
kk tem que ter permissão, ser mutado ai depois é foda kk, cara so tenho 2 duvidas, o slide ta tal qual o que você apresentou lá? e qual a url que eu uso pra ver o slide ? :+1:

**Comment by ythecombinator** [comment]
Cara, o slide aqui tá com umas fixes que fiz depois da apresentação. A url pra ver é a que tem na descrição do repo (http://mabrasil.github.io/slides-flisol-2015).

**Comment by felipesousa** [comment]
digo no sentido de eu baixar e rodar localmente se liga. tem como tu atualizar ele ai pra eu baixar tal qual como tu apresentou  ?

**Comment by ythecombinator** [comment]
Cara, depois que tu roda o _gulp_, ele serve em `localhost:3000`. A cada alteração que tu faz (imagens, marcação, estilos, ou js mesmo) ele já compila novamente e já serve.

**Comment by felipesousa** [comment]
hm, entao no caso, eu pego os slides que nao estao completos e faço somente alterar? 
e outra duvida, no caso a cada (skyp) que eu dou é uma nova tag <section>?

**Comment by ythecombinator** [comment]
Cara, faz assim:
1. Dá uma lida no `src/templates/index.jade` pra tu entender como a ordenação se baseia em includes.
2. Dá uma olhada na pasta `/slides` enquanto tu assiste a apresentação pra tu ver como cada slide em _jade_ é renderizado pra HTML - isso vai te ajudar a entender mais a sintaxe de _jade_.
3. Então, eu sugiro que tu apague os slides porque, se tu for alterando, pode ir misturando o conteúdo das apresentações - o que confunde. BTW, se quiser só ir editando, de boa.

Com relação a segunda, não sei se entendi a pergunta direito, mas assim.
- Cada novo **slide** (que vai se navegado horizontalmente) é um novo arquivo `.jade` que tu vai editar e tal - e não esquece de adicionar em `src/templates/index.jade` fazendo os includes na ordem da apresentação.
- Cada novo **slide vertical** (que vai se navegado verticalmente, dentro de um **slide**), é uma `section.sec-slide` dentro da `section` do slide que tu tá trabalhando.
- Cada novo **fragment** (que faz com que elementos apareçam conforme tu navega, dentro do slide - dando mais interatividade), tu tem que adicionar `.fragment` no elemento. Ex.: se tu quer colocar uma lista, mas não quer que ela seja exibida de um vez só, e sim a cada keypress, então tu faz:

``` jade
ul
    li.fragment Item 1
    li.fragment Item 2
    li.fragment Item 3
```

**Comment by felipesousa** [comment]
Crl, mano valeu mesmo pelo review foda que você deu! Obrigado pelas dicas, a apresentação vai ocorrer Quarta ou Quinta! Obrigado ai pelas dicas e valeu ;) qualquer coisa eu te chamarei aqui

**Comment by ythecombinator** [comment]
Estamos aí!

**Comment by ythecombinator** [comment]
Qualquer nova dúvida, pode abrir outra issue :smile:
